apiVersion: v1
kind: Secret
metadata:
  name: db-config
type: Opaque
data:
  DB_HOST: {{ .Values.db.host }}
  DB_USER: {{ .Values.db.username }}
  DB_PASS: {{ .Values.db.password }}
  DB_DB: {{ .Values.db.host }}