apiVersion: v1
kind: Secret
metadata:
  name: "db-config-{{ template "footpatrol.fullname" . }}"
type: Opaque
data:
  DB_HOST: {{ .Values.db.host | b64enc }}
  DB_USER: {{ .Values.db.username | b64enc }}
  DB_PASS: {{ .Values.db.password | b64enc }}
  DB_DB: {{ .Values.db.database | b64enc }}