{{- if .Values.dockercfg -}}
apiVersion: v1
data:
  .dockercfg: {{ .Values.dockercfg }}
kind: Secret
metadata:
  name: "capstone-reg-secret-{{ template "footpatrol.fullname" . }}"
type: kubernetes.io/dockercfg
{{- end -}}