apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Values.docs.name }}-{{ template "footpatrol.fullname" . }}"
  labels:
    app: {{ .Values.appLabel }}
    name: "{{ template "footpatrol.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ .Values.docs.name }}
spec:
  replicas: {{ .Values.docs.replicas }}
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
        name: "{{ template "footpatrol.fullname" . }}"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        component: {{ .Values.docs.name }}
    spec:
      imagePullSecrets:
      - name: capstone-reg-secret
      containers:
      - image: "{{ .Values.imageBase }}/{{ .Values.docs.imageName }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: {{ .Values.docs.internalPort }}
      restartPolicy: Always