version: "2"         # required to adjust maintainability checks
plugins:
  structure:
    enabled: false
  duplication:
    enabled: false
  fixme:
    enabled: true
    exclude_patterns:
    - src/backend/
    - src/dispatch-website/
  