# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service

# Ensure that the back passes its tests first since the front relies on the back
stages:
  - test
  - build
  - container_build
  - deploy


#################################
#                               #
#            TESTS              #
#                               #
#################################

# Code common to the front- and back-end tests
.test_common: &test_common
  stage: test
  # This folder is cached between builds
  # http://docs.gitlab.com/ce/ci/yaml/README.html#cache
  except:
  - temp
  - tags
  artifacts:
    expire_in: 2 weeks

.test_docker_common: &test_docker_common  # TODO: Is this necessary if image can be overridden? Figure out how to test mobile
  <<: *test_common
  image: node:8 # TODO: Swap out with a pre-built testing image containing testing frameworks
  tags:
  - docker
  - linux
  coverage: /Lines\s*:\s*(\d*\.?\d+)%/
  variables:
    NODE_ENV: 'test'  # To set Mocha to isolate data
  before_script:
  - npm config set registry http://docker-npm-cache-sonatype-nexus.default.svc.cluster.local:8081/repository/npm-group/ # Setup proxy to stop killing bandwidth
  cache:
    paths:
      - src/*/node_modules/

# This test ensures the back end works
test_backend:
  <<: *test_docker_common
  artifacts:
    paths:
      - src/backend/coverage/
  script:
   - cd src/backend
   - rm package-lock.json
   - npm install
   - npm run lint || true   # Prevents JSHint errors from stopping build
   - npm run coverage
   # TODO: Figure out how to test backend


# This test ensures the front end works
test_dispatch_website:
  <<: *test_docker_common
  artifacts:
    paths:
      - src/dispatch-website/coverage/
  script:
   - cd src/dispatch-website
   - npm install
   - npm run lint || true   # Prevents JSHint errors from stopping build
   - npm run coverage
   # TODO: Figure out how to test Angular


# This test ensures the front end works
# test_mobile:
#   <<: *test_common
#     tags:
#     - ios
#     - android
#   artifacts:
#     paths:
#       - src/mobile-app/coverage/
#   script:
#    - cd src/mobile-app
#    # TODO: Figure out how to CI test mobile app


#################################
#                               #
#            BUILD              #
#                               #
#################################

# Common components to build jobs
.build_common: &build_common
  stage: build
  dependencies: []

.build_docker_common: &build_docker_common
  <<: *build_common
  image: node:8
  before_script:
  - npm config set registry http://docker-npm-cache-sonatype-nexus.default.svc.cluster.local:8081/repository/npm-group/ # Setup proxy to stop killing bandwidth
  tags:
  - docker
  - linux

.build_review_common: &build_review_common
  when: manual
  artifacts:
    expire_in: 1 day
  except:
    - master
    - develop
    - tags

.build_deploy_common: &build_deploy_common
  artifacts:
    expire_in: 2 weeks
  only:
    - master
    - develop
  

### --- REVIEW --- ###

# This job builds the client-side code for review
build_review_website:
  <<: *build_review_common
  <<: *build_docker_common
  artifacts:
    paths:
     -  src/dispatch-website  # TODO: Remember to filter this better after figuring out how to compile this app
  script:
   - cd src/dispatch-website
   - npm install --production
   # TODO: Figure out how to compile this app


# This job builds the client-side code for review
build_review_backend:
  <<: *build_review_common
  <<: *build_docker_common
  artifacts:
    paths:
     -  src/backend  # TODO: Remember to filter this better after figuring out how to compile this app
  script:
   - cd src/backend
   - npm install --production
   # TODO: Figure out how to compile this app


# build_review_mobile:  # TODO: Figure this out
#   <<: *build_review_common
#   tags:
#   - ios
#   - android
#   artifacts:
#     paths:
#      -  src/mobile-app  # TODO: Remember to filter this better after figuring out how to compile this app
#   script:
#    - cd src/mobile-app
#    # TODO: Figure out how to compile this app


### --- DEPLOYMENT --- ###

# This job builds the client-side web app code for deployment
build_website:
  <<: *build_deploy_common
  <<: *build_docker_common
  artifacts:
    paths:
     -  src/dispatch-website  # TODO: Remember to filter this better after figuring out how to compile this app
  script:
   - cd src/dispatch-website
   - npm install --production
   # TODO: Figure out how to compile this app


# This job builds the backend API for deployment
build_backend:
  <<: *build_deploy_common
  <<: *build_docker_common
  artifacts:
    paths:
     -  src/backend  # TODO: Remember to filter this better after figuring out how to compile this app
  script:
   - cd src/backend
   - npm install --production
   # TODO: Figure out how to compile this app


# This job builds the mobile app for deployment
# build_mobile:
#   <<: *build_deploy_common
#   tags:
#   - ios
#   - android
#   artifacts:
#     paths:
#      -  src/mobile-app  # TODO: Remember to filter this better after figuring out how to compile this app
#   script:
#    - cd src/mobile-app
#    # TODO: Figure out how to compile this app


#################################
#                               #
#        CONTAINER_BUILD        #
#                               #
#################################

# Common components to build jobs
.container_build_common: &container_build_common
  stage: container_build
  tags:
  - docker_build
  - linux
  

### --- REVIEW --- ###

# This job builds the client-side code for review
container_build_review_website:
  <<: *container_build_common
  dependencies:
  - build_review_website
  script:
   - cd src/dispatch-website
   - docker build -t registry.incode.ca/capstone/foot-patrol/website:$CI_COMMIT_REF_SLUG .
   - docker push registry.incode.ca/capstone/foot-patrol/website:$CI_COMMIT_REF_SLUG


# This job builds the client-side code for review
container_build_review_backend:
  <<: *container_build_common
  dependencies:
  - build_review_backend
  script:
   - cd src/backend
   - docker build -t registry.incode.ca/capstone/foot-patrol/backend:$CI_COMMIT_REF_SLUG .
   - docker push registry.incode.ca/capstone/foot-patrol/backend:$CI_COMMIT_REF_SLUG


### --- DEPLOYMENT --- ###

# This job builds the client-side web app code for deployment
container_build_website:
  <<: *container_build_common
  dependencies:
  - build_website
  script:
   - cd src/dispatch-website
   - docker build -t registry.incode.ca/capstone/foot-patrol/website:$CI_COMMIT_REF_SLUG .
   - docker push registry.incode.ca/capstone/foot-patrol/website:$CI_COMMIT_REF_SLUG


# This job builds the backend API for deployment
container_build_backend:
  <<: *container_build_common
  dependencies:
  - build_backend
  script:
   - cd src/backend
   - docker build -t registry.incode.ca/capstone/foot-patrol/backend:$CI_COMMIT_REF_SLUG .
   - docker push registry.incode.ca/capstone/foot-patrol/backend:$CI_COMMIT_REF_SLUG


#################################
#                               #
#            DEPLOY             #
#                               #
#################################

# Common components to deploy jobs
.deploy_common: &deploy_common
  stage: deploy
  variables:
    DOMAIN: capstone.incode.ca
  image: registry.incode.ca/capstone/foot-patrol/kubectl_deployer:latest


### --- REVIEW --- ###

# TODO: Setup deployment for mobile
# This job takes the contents from the build review jobs, then deploys everything
deploy_review:
  <<: *deploy_common
  dependencies:
   - build_review_website
   - build_review_backend
  script:
    - helm install --namespace capstone-deploy --name $CI_ENVIRONMENT_SLUG --set ingress.hosts[0].name=$CI_ENVIRONMENT_SLUG.$DOMAIN,appLabel=$CI_ENVIRONMENT_SLUG
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.$DOMAIN/
    on_stop: shutdown_review
  except:
    - master
    - tags


# This job stops the deployment containers
shutdown_review:
  <<: *deploy_common
  dependencies: []
  variables:
      GIT_STRATEGY: None
  when: manual
  script:
    - helm delete --purge $CI_ENVIRONMENT_SLUG
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.$DOMAIN/
    action: stop
  except:
    - master
    - tags


### --- PRODUCTION --- ###

# This job takes the contents from the previous job, builds them into a docker image, then deploys everything
production:
  <<: *deploy_common
  dependencies:
   - build_website
   - build_backend
  script:
    - helm install --namespace capstone-deploy --name $CI_ENVIRONMENT_SLUG --set ingress.hosts[0].name=$DOMAIN,appLabel=$CI_ENVIRONMENT_SLUG
  environment:
    name: production
    url: http://$DOMAIN/
    on_stop: shutdown
  only:
    - master


# This job stops the deployment containers
shutdown:
  <<: *deploy_common
  dependencies: []
  variables:
      GIT_STRATEGY: None
  when: manual
  script:
    - helm delete --purge $CI_ENVIRONMENT_SLUG
  environment:
    name: production
    url: http://$DOMAIN/
    action: stop
  only:
    - master
