# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service

# Ensure that the back passes its tests first since the front relies on the back
stages:
  - pretest
  - test
  - build
  - containerize
  - deploy

variables:
  # NPM_CACHE: http://docker-npm-cache-sonatype-nexus.default.svc.cluster.local:8081/repository/npm-group/
  NAMESPACE: capstone-deploy
  DOMAIN: capstone.incode.ca
  DB_CONFIG: db.host=${CI_ENVIRONMENT_SLUG}-mysql.${NAMESPACE}.svc.cluster.local,db.password=$DB_PASS,mysql.mysqlPassword=$DB_PASS,mysql.mysqlRootPassword=$DB_ROOT_PASS
  DB_HOST: ${CI_ENVIRONMENT_SLUG}-mysql.${NAMESPACE}.svc.cluster.local
  DB_SLEEP_TIME: 60   # Time to wait for DB to start up

  # Variables in Gitlab CI:
  # $DB_PASS: password for footpatrol account
  # $DB_ROOT_PASS: password for root account

.quality_base: &quality_base
  stage: pretest
  tags:
  - dind
  except:
  - temp
  - tags
  artifacts:
    expire_in: 1 hour
  image: docker:latest
  services:
  - name: docker:dind
    command: ["--registry-mirror=http://registry.internal.incode.ca:80"]
  artifacts:
   paths:
   - top.json
   - backend.json
   - frontend.json
  before_script:
  - docker pull codeclimate/codeclimate

quality_top:
  <<: *quality_base
  script:
  - docker run --env CODECLIMATE_CODE="$PWD" --env DOCKER_HOST="$DOCKER_PORT" --volume "$PWD":/code --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f json > top.json

quality_backend:
  <<: *quality_base
  script:
  - cd src/backend
  - docker run --env CODECLIMATE_CODE="$PWD" --env DOCKER_HOST="$DOCKER_PORT" --volume "$PWD":/code --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f json > ../../backend.json

quality_frontend:
  <<: *quality_base
  cache:
    key: quality_frontend
    paths:
    - src/dispatch-website/node_modules/
  image: registry.incode.ca/capstone/foot-patrol/node-docker:8-17.12    # Merged node:8-alpine and docker:17.12
  script:
  - cd src/dispatch-website
  - npm install # Workaround for https://github.com/tkqubo/codeclimate-tslint/issues/26
  - docker run --env CODECLIMATE_CODE="$PWD" --env DOCKER_HOST="$DOCKER_PORT" --volume "$PWD":/code --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f json > ../../frontend.json

#################################
#                               #
#            TESTS              #
#                               #
#################################

# Code common to the front- and back-end tests
.test_common: &test_common
  stage: test
  except:
  - temp
  - tags
  artifacts:
    expire_in: 2 weeks

.test_docker_common: &test_docker_common
  <<: *test_common
  image: node:8
  dependencies: []
  tags:
  - docker
  - linux
  coverage: /Functions\s*:\s*(\d*\.?\d+)%/
  variables:
    NODE_ENV: 'test'  # To set Mocha to isolate data
  # before_script:
  # - npm config set registry $NPM_CACHE # Setup proxy to stop killing bandwidth

# This test ensures the back end works
test_backend:
  <<: *test_docker_common
  artifacts:
    paths:
      - src/backend/coverage/
  cache:
    key: backend
    paths:
      - src/backend/node_modules/
  script:
   - cd src/backend
   - rm package-lock.json || true   # So that cache server works
   - npm install
   - npm run coverage


# This test ensures the front end works
test_dispatch_website:
  <<: *test_docker_common
  image: amio/node-chrome   # Contains both Node 8 and Chrome (https://incode.ca/capstone/docker-node-chrome mirrored from https://github.com/amio/docker-node-chrome)
  artifacts:
    paths:
      - src/dispatch-website/coverage/
  cache:
    key: frontend
    paths:
      - src/dispatch-website/node_modules/
  script:
   - cd src/dispatch-website
   - rm package-lock.json || true   # So that cache server works
   - npm install
   - npm run coverage
   # - npm run e2e          # TODO: Do we want e2e testing?


# Handle linting and other code quality errors
codequality:
  <<: *test_common
  image: python:3
  dependencies:
  - quality_top
  - quality_frontend
  - quality_backend
  tags:
  - docker
  - linux
  artifacts:
   paths:
   - codeclimate.json
  script:
   - python join.py top.json backend.json frontend.json codeclimate.json

# This test ensures the front end works
# test_mobile:
#   <<: *test_common
#     tags:
#     - ios
#     - android
#   artifacts:
#     paths:
#       - src/mobile-app/coverage/
#   script:
#    - cd src/mobile-app
#    # TODO: Figure out how to CI test mobile app


#################################
#                               #
#            BUILD              #
#                               #
#################################

# Common components to build jobs
.build_common: &build_common
  stage: build
  dependencies: []

.build_docker_common: &build_docker_common
  <<: *build_common
  image: registry.incode.ca/capstone/foot-patrol/node_type:8
  tags:
  - docker
  - linux

.build_review_common: &build_review_common
  artifacts:
    expire_in: 1 day
  except:
    - master
    - develop
    - tags

.build_deploy_common: &build_deploy_common
  artifacts:
    expire_in: 2 weeks
  only:
    - master
    - develop

.website: &website
  artifacts:
    paths:
     - src/dispatch-website/dist/
  cache:
    policy: pull
    key: frontend
    paths:
      - src/dispatch-website/node_modules/
  script:
   - cd src/dispatch-website
   - npm install
   - if [ $CI_COMMIT_REF_NAME == "master" ]; then export PUBLIC_URL="$DOMAIN"; elif [ $CI_COMMIT_REF_NAME == "develop" ]; then export PUBLIC_URL="staging.$DOMAIN"; else export PUBLIC_URL="$CI_COMMIT_REF_SLUG.$DOMAIN"; fi
   - envsubst < src/environments/environment.prod.ts > src/environments/environment.prod2.ts # Do a replacement of environment.prod.ts of ${PUBLIC_URL}
   - mv src/environments/environment.prod2.ts src/environments/environment.prod.ts
   - npm run build -- --prod --env=prod  # Do a replacement of environment.prod.ts of ${PUBLIC_URL}

.backend: &backend
  artifacts:
    paths:
     - src/backend/dist/
     - src/backend/node_modules/
     - src/backend/docs/
     - src/backend/apidocs/
  cache:
    policy: pull
    key: backend
    paths:
      - src/backend/node_modules/
  script:
   - cd src/backend
   - npm install typedoc apidoc # Can't hurt, will get caught by cache if available
   - npm run docs
   - npm prune --production   # Remove non-production packages that came in with the cache
   - npm install --production # If no cache
   - npm run build_production


### --- REVIEW --- ###

# This job builds the client-side code for review
build_review_website:
  <<: *build_review_common
  <<: *build_docker_common
  <<: *website

# This job builds the client-side code for review
build_review_backend:
  <<: *build_review_common
  <<: *build_docker_common
  <<: *backend

# build_review_mobile:  # TODO: Figure this out
#   <<: *build_review_common
#   tags:
#   - ios
#   - android
#   artifacts:
#     paths:
#      -  src/mobile-app  # TODO: Remember to filter this better after figuring out how to compile this app
#   script:
#    - cd src/mobile-app
#    # TODO: Figure out how to compile this app


### --- DEPLOYMENT --- ###

# This job builds the client-side web app code for deployment
build_website:
  <<: *build_deploy_common
  <<: *build_docker_common
  <<: *website

# This job builds the backend API for deployment
build_backend:
  <<: *build_deploy_common
  <<: *build_docker_common
  <<: *backend


# This job builds the mobile app for deployment
# build_mobile:
#   <<: *build_deploy_common
#   tags:
#   - ios
#   - android
#   artifacts:
#     paths:
#      -  src/mobile-app  # TODO: Remember to filter this better after figuring out how to compile this app
#   script:
#    - cd src/mobile-app
#    # TODO: Figure out how to compile this app


#################################
#                               #
#         Containerize          #
#                               #
#################################

# Common components to build jobs
.containerize_common: &containerize_common
  stage: containerize
  tags:
  - docker_build
  - linux
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

.containerize_review_common: &containerize_review_common
  except:
    - master
    - develop
    - tags

.containerize_deploy_common: &containerize_deploy_common
  only:
    - master
    - develop
  
.web_container: &web_container
  script:
   - cd src/dispatch-website
   - docker build --no-cache -t $CI_REGISTRY_IMAGE/webapp:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA .
   - docker push $CI_REGISTRY_IMAGE/webapp:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA

.back_container: &back_container
  script:
   - cd src/backend
   - docker build --no-cache -t $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA .
   - docker push $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA

.back_docs_container: &back_docs_container
  script:
  - cd src/backend
  - docker build --file Dockerfile_docs -t $CI_REGISTRY_IMAGE/backend_docs:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA .
  - docker push $CI_REGISTRY_IMAGE/backend_docs:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA

### --- REVIEW --- ###

# This job builds the client-side code for review
containerize_review_website:
  <<: *containerize_common
  <<: *containerize_review_common
  <<: *web_container
  dependencies:
  - build_review_website


# This job builds the server-side code for review
containerize_review_backend:
  <<: *containerize_common
  <<: *containerize_review_common
  <<: *back_container
  dependencies:
  - build_review_backend

# This job builds the docs for the server-side code
containerize_review_backend_docs:
  <<: *containerize_common
  <<: *containerize_review_common
  <<: *back_docs_container
  dependencies:
  - build_review_backend


### --- DEPLOYMENT --- ###

# This job builds the client-side web app code for deployment
containerize_website:
  <<: *containerize_common
  <<: *containerize_deploy_common
  <<: *web_container
  dependencies:
  - build_website


# This job builds the backend API for deployment
containerize_backend:
  <<: *containerize_common
  <<: *containerize_deploy_common
  <<: *back_container
  dependencies:
  - build_backend

# This job builds the docs for the backend API for deployment
containerize_backend_docs:
  <<: *containerize_common
  <<: *containerize_deploy_common
  <<: *back_docs_container
  dependencies:
  - build_backend


#################################
#                               #
#            DEPLOY             #
#                               #
#################################

# Common components to deploy jobs
.deploy_common: &deploy_common
  stage: deploy
  dependencies: []
  tags:
    - docker
    - linux
  variables:
    COMMON_INSTALL_HELM: --tiller-namespace $NAMESPACE --namespace ${NAMESPACE} --set appLabel=$CI_ENVIRONMENT_SLUG,dockercfg=$DOCKERCFG,imageTag=$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA,imageBase=$CI_REGISTRY_IMAGE
    HELM_CHART: deploy/charts/foot-patrol
  before_script:
  - helm init --client-only --tiller-namespace $NAMESPACE
  - helm repo add stable https://kubernetes-charts.storage.googleapis.com/
  image: $CI_REGISTRY_IMAGE/kubectl_deployer:latest


### --- REVIEW --- ###

# TODO: Setup deployment for mobile
# This job takes the contents from the build review jobs, then deploys everything
deploy_review:
  <<: *deploy_common
  script:
    - helm dependency build $HELM_CHART
    - helm upgrade $CI_ENVIRONMENT_SLUG $HELM_CHART --install $COMMON_INSTALL_HELM --set backend.replicas=1,webapp.replicas=1,ingress.hosts={"$CI_COMMIT_REF_SLUG.$DOMAIN"},$DB_CONFIG
    - cd src/backend
    - until [ $(kubectl get pods -n $NAMESPACE | grep "$CI_ENVIRONMENT_SLUG-mysql" | grep -o "1/1") ]; do echo "mysql not ready..."; sleep 15; done
    - sleep 30  # Wait out any bugs
    - mysql -h $DB_HOST -u root --password=$DB_ROOT_PASS < sql_statements.sql
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_COMMIT_REF_SLUG.$DOMAIN/
    on_stop: shutdown_review
  except:
    - master
    - develop
    - tags


# This job stops the deployment containers
shutdown_review:
  <<: *deploy_common
  variables:
      GIT_STRATEGY: None
  when: manual
  script:
    - helm delete --purge $CI_ENVIRONMENT_SLUG --tiller-namespace $NAMESPACE
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_COMMIT_REF_SLUG.$DOMAIN/
    action: stop
  except:
    - master
    - develop
    - tags

### --- Staging --- ###

# TODO: Setup deployment for mobile
# This job takes the contents from the previous job, builds them into a docker image, then deploys everything
staging:
  <<: *deploy_common
  script:
    - helm dependency build $HELM_CHART
    - helm upgrade $CI_ENVIRONMENT_SLUG $HELM_CHART --install $COMMON_INSTALL_HELM --set ingress.hosts={"staging.$DOMAIN"},$DB_CONFIG
    - cd src/backend
    - until [ $(kubectl get pods -n $NAMESPACE | grep "$CI_ENVIRONMENT_SLUG-mysql" | grep -o "1/1") ]; do echo "mysql not ready..."; sleep 15; done
    - sleep 30  # Wait out any bugs
    - mysql -h $DB_HOST -u root --password=$DB_ROOT_PASS < sql_statements.sql
  environment:
    name: staging
    url: http://staging.$DOMAIN/
    on_stop: shutdown_staging
  only:
    - develop


# This job stops the deployment containers
shutdown_staging:
  <<: *deploy_common
  variables:
      GIT_STRATEGY: None
  when: manual
  script:
    - helm delete --purge $CI_ENVIRONMENT_SLUG --tiller-namespace $NAMESPACE
  environment:
    name: staging
    url: http://staging.$DOMAIN/
    action: stop
  only:
    - develop

### --- PRODUCTION --- ###

# TODO: Setup deployment for mobile
# This job takes the contents from the previous job, builds them into a docker image, then deploys everything
production:
  <<: *deploy_common
  script:
    - helm dependency build $HELM_CHART
    - helm upgrade $CI_ENVIRONMENT_SLUG $HELM_CHART --install $COMMON_INSTALL_HELM --set ingress.hosts={"$DOMAIN"},$DB_CONFIG
    - cd src/backend
    - until [ $(kubectl get pods -n $NAMESPACE | grep "$CI_ENVIRONMENT_SLUG-mysql" | grep -o "1/1") ]; do echo "mysql not ready..."; sleep 15; done
    - sleep 30  # Wait out any bugs
    - mysql -h $DB_HOST -u root --password=$DB_ROOT_PASS < sql_statements.sql
  environment:
    name: production
    url: http://$DOMAIN/
    on_stop: shutdown
  only:
    - master


# This job stops the deployment containers
shutdown:
  <<: *deploy_common
  variables:
      GIT_STRATEGY: None
  when: manual
  script:
    - helm delete --purge $CI_ENVIRONMENT_SLUG --tiller-namespace $NAMESPACE
  environment:
    name: production
    url: http://$DOMAIN/
    action: stop
  only:
    - master
