# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service

# Ensure that the back passes its tests first since the front relies on the back
stages:
  - test
  - build
  - containerize
  - deploy

variables:
  NPM_CACHE: http://docker-npm-cache-sonatype-nexus.default.svc.cluster.local:8081/repository/npm-group/
  TILLER_NAMESPACE: capstone-deploy
  DOMAIN: capstone.incode.ca


#################################
#                               #
#            TESTS              #
#                               #
#################################

# Code common to the front- and back-end tests
.test_common: &test_common
  stage: test
  except:
  - temp
  - tags
  artifacts:
    expire_in: 2 weeks

.test_docker_common: &test_docker_common
  <<: *test_common
  image: node:8
  tags:
  - docker
  - linux
  coverage: /Lines\s*:\s*(\d*\.?\d+)%/
  variables:
    NODE_ENV: 'test'  # To set Mocha to isolate data
  before_script:
  - npm config set registry $NPM_CACHE # Setup proxy to stop killing bandwidth
  - mv .npm/ /root/.npm   # To cache miscellaneous npm binaries
  - pushd .
  after_script:
  - popd
  - cp /root/.npm .

# This test ensures the back end works
test_backend:
  <<: *test_docker_common
  artifacts:
    paths:
      - src/backend/coverage/
  cache:
    key: backend_npm
    paths:
      - src/backend/node_modules/
      - .npm/
  script:
   - cd src/backend
   - rm package-lock.json || true   # So that cache server works
   - npm install
   - npm run lint || true   # Prevents JSHint errors from stopping build
   - npm run coverage


# This test ensures the front end works
test_dispatch_website:
  <<: *test_docker_common
  artifacts:
    paths:
      - src/dispatch-website/coverage/
  cache:
    key: angular_npm
    paths:
      - src/dispatch-website/node_modules/
      - .npm/
  script:
   - cd src/dispatch-website
   - rm package-lock.json || true   # So that cache server works
   - npm install
   - npm run lint || true   # Prevents JSHint errors from stopping build
  #  - npm run coverage     # TODO: Figure out how to test Angular (https://gist.github.com/coolman565/f392f08cf90e90db18dd06e7d3f5f41c)


# This test ensures the front end works
# test_mobile:
#   <<: *test_common
#     tags:
#     - ios
#     - android
#   artifacts:
#     paths:
#       - src/mobile-app/coverage/
#   script:
#    - cd src/mobile-app
#    # TODO: Figure out how to CI test mobile app


#################################
#                               #
#            BUILD              #
#                               #
#################################

# Common components to build jobs
.build_common: &build_common
  stage: build
  dependencies: []

.build_docker_common: &build_docker_common
  <<: *build_common
  image: node:8
  before_script:
  - npm config set registry $NPM_CACHE # Setup proxy to stop killing bandwidth
  - mv .npm/ /root/.npm   # To cache miscellaneous npm binaries
  - npm install typescript -g
  - pushd .
  after_script:
  - popd
  - cp /root/.npm .
  tags:
  - docker
  - linux

.build_review_common: &build_review_common
  artifacts:
    expire_in: 1 day
  except:
    - master
    - develop
    - tags

.build_deploy_common: &build_deploy_common
  artifacts:
    expire_in: 2 weeks
  only:
    - master
    - develop
  

### --- REVIEW --- ###

# This job builds the client-side code for review
build_review_website:
  <<: *build_review_common
  <<: *build_docker_common
  artifacts:
    paths:
     -  src/dispatch-website/dist/
  cache:
    key: angular_npm
    policy: pull
    paths:
      - src/dispatch-website/node_modules/
      - .npm/
  script:
   - cd src/dispatch-website
   - npm install --production
   # TODO: Figure out how to compile this app


# This job builds the client-side code for review
build_review_backend:
  <<: *build_review_common
  <<: *build_docker_common
  artifacts:
    paths:
     -  src/backend/dist/
  cache:
    key: backend_npm
    policy: pull
    paths:
      - src/backend/node_modules/
      - .npm/
  script:
   - cd src/backend
   - npm install --production
   - npm run build_production


# build_review_mobile:  # TODO: Figure this out
#   <<: *build_review_common
#   tags:
#   - ios
#   - android
#   artifacts:
#     paths:
#      -  src/mobile-app  # TODO: Remember to filter this better after figuring out how to compile this app
#   script:
#    - cd src/mobile-app
#    # TODO: Figure out how to compile this app


### --- DEPLOYMENT --- ###

# This job builds the client-side web app code for deployment
build_website:
  <<: *build_deploy_common
  <<: *build_docker_common
  artifacts:
    paths:
     -  src/dispatch-website/dist/
  cache:
    key: angular_npm
    policy: pull
    paths:
      - src/dispatch-website/node_modules/
      - .npm/
  script:
   - cd src/dispatch-website
   - npm install --production
   # TODO: Figure out how to compile this app


# This job builds the backend API for deployment
build_backend:
  <<: *build_deploy_common
  <<: *build_docker_common
  artifacts:
    paths:
     -  src/backend/dist/
  cache:
    key: backend_npm
    policy: pull
    paths:
      - src/backend/node_modules/
      - .npm/
  script:
   - cd src/backend
   - npm install --production
   - npm run build_production


# This job builds the mobile app for deployment
# build_mobile:
#   <<: *build_deploy_common
#   tags:
#   - ios
#   - android
#   artifacts:
#     paths:
#      -  src/mobile-app  # TODO: Remember to filter this better after figuring out how to compile this app
#   script:
#    - cd src/mobile-app
#    # TODO: Figure out how to compile this app


#################################
#                               #
#         Containerize          #
#                               #
#################################

# Common components to build jobs
.containerize_common: &containerize_common
  stage: containerize
  tags:
  - docker_build
  - linux
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

.containerize_review_common: &containerize_review_common
  except:
    - master
    - develop
    - tags

.containerize_deploy_common: &containerize_deploy_common
  only:
    - master
    - develop
  

### --- REVIEW --- ###

# This job builds the client-side code for review
containerize_review_website:
  <<: *containerize_common
  <<: *containerize_review_common
  dependencies:
  - build_review_website
  script:
   - cd src/dispatch-website
   - docker build -t $CI_REGISTRY_IMAGE/website:$CI_COMMIT_REF_SLUG .
   - docker push $CI_REGISTRY_IMAGE/website:$CI_COMMIT_REF_SLUG


# This job builds the client-side code for review
containerize_review_backend:
  <<: *containerize_common
  <<: *containerize_review_common
  dependencies:
  - build_review_backend
  script:
   - cd src/backend
   - docker build -t $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG .
   - docker push $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG


### --- DEPLOYMENT --- ###

# This job builds the client-side web app code for deployment
containerize_website:
  <<: *containerize_common
  <<: *containerize_deploy_common
  dependencies:
  - build_website
  script:
   - cd src/dispatch-website
   - docker build -t $CI_REGISTRY_IMAGE/website:$CI_COMMIT_REF_SLUG .
   - docker push $CI_REGISTRY_IMAGE/website:$CI_COMMIT_REF_SLUG


# This job builds the backend API for deployment
containerize_backend:
  <<: *containerize_common
  <<: *containerize_deploy_common
  dependencies:
  - build_backend
  script:
   - cd src/backend
   - docker build -t $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG .
   - docker push $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG


#################################
#                               #
#            DEPLOY             #
#                               #
#################################

# Common components to deploy jobs
.deploy_common: &deploy_common
  stage: deploy
  dependencies: []
  tags:
    - docker
    - linux
  variables:
    COMMON_INSTALL_HELM: --tiller-namespace $TILLER_NAMESPACE --namespace capstone-deploy --name $CI_ENVIRONMENT_SLUG --set appLabel=$CI_ENVIRONMENT_SLUG,dockercfg=$DOCKERCFG,imageTag=$CI_COMMIT_REF_SLUG,imageBase=$CI_REGISTRY_IMAGE
    HELM_CHART: deploy/charts/foot-patrol
  before_script:
  - helm init --client-only --tiller-namespace $TILLER_NAMESPACE
  - helm repo add stable https://kubernetes-charts.storage.googleapis.com/
  image: $CI_REGISTRY_IMAGE/kubectl_deployer:latest


### --- REVIEW --- ###

# TODO: Setup deployment for mobile
# This job takes the contents from the build review jobs, then deploys everything
deploy_review:
  <<: *deploy_common
  script:
    - helm dependency build $HELM_CHART
    - helm install $COMMON_INSTALL_HELM --set ingress.hosts={"$CI_ENVIRONMENT_SLUG.$DOMAIN"} $HELM_CHART
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.$DOMAIN/
    on_stop: shutdown_review
  except:
    - master
    - develop
    - tags


# This job stops the deployment containers
shutdown_review:
  <<: *deploy_common
  variables:
      GIT_STRATEGY: None
  when: manual
  script:
    - helm delete --purge $CI_ENVIRONMENT_SLUG --tiller-namespace $TILLER_NAMESPACE
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.$DOMAIN/
    action: stop
  except:
    - master
    - develop
    - tags

### --- Staging --- ###

# This job takes the contents from the previous job, builds them into a docker image, then deploys everything
staging:
  <<: *deploy_common
  script:
    - helm dependency build $HELM_CHART
    - helm install $COMMON_INSTALL_HELM --set ingress.hosts={staging.$DOMAIN} $HELM_CHART
  environment:
    name: staging
    url: http://staging.$DOMAIN/
    on_stop: shutdown_staging
  only:
    - develop


# This job stops the deployment containers
shutdown_staging:
  <<: *deploy_common
  variables:
      GIT_STRATEGY: None
  when: manual
  script:
    - helm delete --purge $CI_ENVIRONMENT_SLUG --tiller-namespace $TILLER_NAMESPACE
  environment:
    name: staging
    url: http://staging.$DOMAIN/
    action: stop
  only:
    - develop

### --- PRODUCTION --- ###

# This job takes the contents from the previous job, builds them into a docker image, then deploys everything
production:
  <<: *deploy_common
  script:
    - helm dependency build $HELM_CHART
    - helm install $COMMON_INSTALL_HELM --set ingress.hosts={$DOMAIN} $HELM_CHART
  environment:
    name: production
    url: http://$DOMAIN/
    on_stop: shutdown
  only:
    - master


# This job stops the deployment containers
shutdown:
  <<: *deploy_common
  variables:
      GIT_STRATEGY: None
  when: manual
  script:
    - helm delete --purge $CI_ENVIRONMENT_SLUG --tiller-namespace $TILLER_NAMESPACE
  environment:
    name: production
    url: http://$DOMAIN/
    action: stop
  only:
    - master
