imageBase: registry.incode.ca/capstone/foot-patrol
imageTag: "master"                      # Replace me!
imagePullPolicy: Always
appLabel: replaceme                     # Replace me!

# dockercfg: base-64-encoded docker config.json file here

# Database connection parameters
db:
  host: host                            # Replace me!
  username: footpatrol
  password: insertmeatruntime           # Replace me!
  database: foot_patrol

# For the mysql dependency chart
mysql:
  mysqlUser: footpatrol
  mysqlDatabase: foot_patrol
  mysqlPassword: insertmeatruntime      # Replace me!
  mysqlRootPassword: insertmeatruntime  # Replace me!

backend:
  name: backend
  imageName: backend
  externalPort: 80
  internalPort: 80
  replicas: 2

webapp:
  name: webapp
  imageName: webapp
  externalPort: 80
  internalPort: 80
  replicas: 2

docs:
  name: backend-docs
  imageName: backend_docs
  externalPort: 80
  internalPort: 80
  replicas: 1

ingress:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |+
      rewrite ^(/backend_docs)$ $1/ redirect;
  enabled: true
  hosts:
  - capstone.incode.ca
  paths:
  - path: /
    serviceName: webapp
    servicePort: 80
  - path: /api/v1
    serviceName: backend
    servicePort: 80
  - path: /backend_docs
    serviceName: backend-docs
    servicePort: 80
  # tls:
  # - secretName: footpatrol-tls
  #   hosts:
  #   - capstone.incode.ca
  #   - "*.capstone.incode.ca"
