apiVersion: v1
kind: Namespace
metadata:
  name: capstone-deploy
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: capstone-deploy-executor
  namespace: capstone-deploy
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: capstone-deployment
  namespace: capstone-deploy
subjects:
- kind: ServiceAccount
  name: ci-machine
  namespace: gitlab-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capstone-deploy-executor
# Create a capstone deployment namespace, and grant all permissions
# inside that namespace to the CI system
