apiVersion: v1
kind: Namespace
metadata:
  name: capstone-deploy
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: capstone-deploy-executor
  namespace: capstone-deploy
rules:
- apiGroups: [ "", "extensions" ]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-executor
  namespace: capstone-deploy
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: capstone-deployment
  namespace: capstone-deploy
subjects:
- kind: ServiceAccount
  name: deployment-executor
  namespace: capstone-deploy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capstone-deploy-executor
