apiVersion: v1
kind: Namespace
metadata:
  name: capstone-deploy
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: capstone-deploy-executor
  namespace: capstone-deploy
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: capstone-deployment
  namespace: capstone-deploy
subjects:
- kind: ServiceAccount
  name: ci-machine
  namespace: gitlab-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capstone-deploy-executor
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: capstone-deployment
  namespace: capstone-deploy
subjects:
- kind: ServiceAccount
  name: default
  namespace: gitlab-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: capstone-deployment-2
  namespace: capstone-deploy
subjects:
- kind: ServiceAccount
  name: default
  namespace: capstone-deploy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
# Create a capstone deployment namespace, and grant all permissions
# inside that namespace to the CI system
# TODO: FIXME: I'm way too broad! I also don't have instructions for helm/tiller in the namespace!
